// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCbJb8VGIfjLXg6WxRdilNOWB7yVzWwDI',
    appId: '1:92364816643:web:7558bb29c4d3cf8d2c2936',
    messagingSenderId: '92364816643',
    projectId: 'chimp-news-29562',
    authDomain: 'chimp-news-29562.firebaseapp.com',
    storageBucket: 'chimp-news-29562.appspot.com',
    measurementId: 'G-S9ZBK94YEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuBOpuaYL3IDMf43K7LYUarNzbIOiWVV8',
    appId: '1:92364816643:android:db61bc520d8a6c7f2c2936',
    messagingSenderId: '92364816643',
    projectId: 'chimp-news-29562',
    storageBucket: 'chimp-news-29562.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUMUs4xIjTK4rAwJseY_PmXp32ly3GcjE',
    appId: '1:92364816643:ios:b0d0be03d8fd839b2c2936',
    messagingSenderId: '92364816643',
    projectId: 'chimp-news-29562',
    storageBucket: 'chimp-news-29562.appspot.com',
    iosBundleId: 'com.chimp.news.chimpNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUMUs4xIjTK4rAwJseY_PmXp32ly3GcjE',
    appId: '1:92364816643:ios:d6d87c558908e6db2c2936',
    messagingSenderId: '92364816643',
    projectId: 'chimp-news-29562',
    storageBucket: 'chimp-news-29562.appspot.com',
    iosBundleId: 'com.chimp.news.chimpNews.RunnerTests',
  );
}
